CREATE TABLE games (
    BGGId INT NOT NULL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description VARCHAR(8000),
    YearPublished INT,
    GameWeight DECIMAL(5 , 4 ) NOT NULL,
    AvgRating DECIMAL(7 , 5 ),
    BayesAvgRating DECIMAL(7 , 5 ) NOT NULL,
    StdDev DECIMAL(7 , 5 ),
    MinPlayers INT NOT NULL,
    MaxPlayers INT NOT NULL,
    ComAgeRec FLOAT,
    LanguageEase FLOAT,
    BestPlayers INT NOT NULL,
    GoodPlayers VARCHAR(255),
    NumOwned INT NOT NULL,
    NumWant INT,
    NumWish INT,
    NumWeightVotes INT,
    MfgPlaytime INT NOT NULL,
    ComMinPlaytime INT NOT NULL,
    ComMaxPlaytime INT NOT NULL,
    MfgAgeRec INT NOT NULL,
    NumUserRatings INT,
    NumComments INT,
    NumAlternates INT,
    NumExpansions INT,
    NumImplementations INT,
    IsReimplementation INT,
    Family VARCHAR(255),
    Kickstarted INT,
    ImagePath VARCHAR(255),
    Rank_boardgame INT,
    Rank_strategygames INT,
    Rank_abstracts INT,
    Rank_familygames INT,
    Rank_thematic INT,
    Rank_cgs INT,
    Rank_wargames INT,
    Rank_partygames INT,
    Rank_childrensgames INT,
    Cat_Thematic INT,
    Cat_Strategy INT,
    Cat_War INT,
    Cat_Family INT,
    Cat_CGS INT,
    Cat_Abstract INT,
    Cat_Party INT,
    Cat_Childrens INT
);

	
